### ISSUE TITLE
Add support for ios binary.

### ISSUE THREAD

**Issue by prabhav-mehra** [0xC0000054/libheif-sharp#10]
I tried using a built .a of libheif and that is causing an error and it is not being picked. I filed the issue in xamarin-macios repo and got the following response.

https://github.com/xamarin/xamarin-macios/issues/19064#issuecomment-1729224033

**Comment by prabhav-mehra** [comment]
@0xC0000054

**Comment by 0xC0000054** [comment]
The response indicates that you are building libheif as a statically-linked library, and it need to be a dynamically-linked library (.dylib?) for .NET to be able to call it.

The missing method errors are probably due to your libheif version being too old, libheif-sharp expects libheif version 1.16.2.
Or there is another issue with the AOT compilation that I am not aware of.

**Comment by prabhav-mehra** [comment]
I think we can use the static lib using "iOS binding projects" and link that to the project (as I have done in the sample repo). I am unaware of the case to link ".dylib" instead of  a ".a". 

Do you reckon the dynamic build (dylib) will work with the existing implementation (i.e. without the __)? 

I can check for the version of the built libheif.

**Comment by 0xC0000054** [comment]
> Do you reckon the dynamic build (dylib) will work with the existing implementation (i.e. without the __)?

Yes, it should.

**Comment by prabhav-mehra** [comment]
@0xC0000054 https://github.com/xamarin/xamarin-macios/issues/19064#issuecomment-1730817195

as suggested, the .dylib will not be supported in Appstore. 

The other option is to use .framework but that requires all dllImport changes. Is it possible to add a check something like `iOS ? __Internal : libheif`and enforce th built lib to be .a for iOS. to get .a from .framework is not an issue.

**Comment by 0xC0000054** [comment]
> Is it possible to add a check something like iOS ? __Internal : libheifand enforce th built lib to be .a for iOS.

I do not think so, the `DllImport` library name is a compile-time constant.
I am not sure what the best way to handle this is.

Looking through the .NET runtime repo issues related to `__Internal`, it appears that you may be able to use [NativeLibrary.SetDllImportResolver](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.setdllimportresolver) in your application to redirect `DllImport` requests for `libheif` to the appropriate native module. See https://github.com/dotnet/runtime/issues/7267#issuecomment-613516993

**Comment by 0xC0000054** [comment]
Here is a test build with the above mentioned DllImportResolver change: [LibHeifSharp-iOS-test.zip](https://github.com/0xC0000054/libheif-sharp/files/12713571/LibHeifSharp-iOS-test.zip)
This version is built against .NET 7.0, in theory it should work on iOS.
