### ISSUE TITLE
How to generate libheif.dll ?

### ISSUE THREAD

**Issue by pol2095** [0xC0000054/libheif-sharp#2]
Hello,

is-it possible to generate `libheif.dll` using Visual Studio ? can-you explain ?

Thanks

**Comment by KWEngine** [comment]
Same here. I generated libheif.dll, libde265.dll and x265.dll (all x64 MinSizeRel builds), copied it to my VS solution directory and I get this exception message:

"Unable to load DLL 'libheif' or one of its dependencies: Die angegebene Prozedur wurde nicht gefunden. (0x8007007F)"
   at LibHeifSharp.Interop.LibHeifNative.heif_get_version_number()
   at LibHeifSharp.LibHeifInfo.GetLibHeifVersionNumber()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at LibHeifSharp.LibHeifInfo.get_VersionNumber()
   at LibHeifSharp.LibHeifVersion.ThrowIfNotSupported()
   at LibHeifSharp.HeifContext..ctor()
   at HEICConverter.MainWindow.Test() in C:\GIT\HEICConverter\MainWindow.xaml.cs:line 58

Could you provide the binaries needed or at least make a list of the needed binaries? I know this is not part of your project, but it would really help users not familiar with C++ to use your bindings.
Cheers!

**Comment by 0xC0000054** [comment]
Based on that error message, you need to place `libheif.dll`, `libde265.dll` and `x265.dll` in the application folder.
The OS expects to find all of the DLL files in the same folder as your executable.

> Could you provide the binaries needed or at least make a list of the needed binaries?

That list of binaries is correct (for HEIC/H265 support).
I just tested the vcpkg `x64-windows` build of libheif, libde265 and x265 and it worked correctly after copying the generated DLL files to the application folder.

I will consider adding vcpkg build instructions for libheif and its dependencies to the library documentation.
The libheif project readme says to use vcpkg when building the library on Windows, but it does not give an example of the commands required to do so.

**Comment by 0xC0000054** [comment]
I added a page with Windows build instructions for libheif to the project documentation site: https://0xc0000054.github.io/libheif-sharp/libheif_windows_build_vcpkg.html

**Comment by KWEngine** [comment]
Thanks a million. Got it to work!
