### ISSUE TITLE
x265 slower

### ISSUE THREAD

**Issue by pol2095** [0xC0000054/libheif-sharp#4]
Hello,

I convert a jpg 1792x1792 px 500 ko to heic, it take 7 sec using x265, on Mac using the native class the same jpg take 1 sec to convert to heic, how x265 is slower ?

Thanks

**Comment by 0xC0000054** [comment]
>  how x265 is slower ?

My guess it that Apple is using a hardware-accelerated encoder, x265 is a software encoder.

**Comment by pol2095** [comment]
Thanks
