### ISSUE TITLE
Invalid input: No 'meta' box

### ISSUE THREAD

**Issue by pol2095** [0xC0000054/libheif-sharp#7]
Hello,

libheif return for some pictures, this message error when I read avif :
`Invalid input: No 'meta' box`

Thanks

**Comment by 0xC0000054** [comment]
> libheif return for some pictures, this message error when I read avif :

Could you upload one of the images?

**Comment by pol2095** [comment]
link to the [avif image](http://pol2095.free.fr/img/test.avif)

I created this image on macOS using [SDWebImageAVIFCoder]( https://github.com/SDWebImage/SDWebImageAVIFCoder)
I can open this image using GIMP on Windows

**Comment by 0xC0000054** [comment]
The file does have a 'meta' box, and I can open it in Photoshop. 

I do not know why you are getting an error message, it may just be some kind of random glitch.

**Comment by pol2095** [comment]
Can you open this [file](http://pol2095.free.fr/img/test.avif) using [libheif-sharp](https://github.com/0xC0000054/libheif-sharp) ?
The problem occur with all files created on macOS.
But I can open this file on Linux using libheif.

**Comment by 0xC0000054** [comment]
> Can you open this file using libheif-sharp?

No, it fails with the missing 'meta' box error.

I found the issue, my file reading code was validating parameters in the wrong order.
The output data pointer can be null for zero-byte reads.

**Comment by pol2095** [comment]
Great job, it work, thanks.
